name: Run Tests

on:
  push:
    branches:
      - main
    paths:
      - services/**
      - .github/workflows/test.yaml
  pull_request:
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Paths Changes Filter
        id: filter
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filters.yaml

  tests:
    runs-on: ubuntu-24.04
    if: ${{ needs.filter.outputs.services != '[]' && needs.filter.outputs.services != '' }}
    needs: filter
    strategy:
      matrix:
        service: ${{ fromJson(needs.filter.outputs.services) }}
      fail-fast: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      
      - name: Setup Nodejs environment
        if: ${{ startsWith(matrix.service, 'services/node') || startsWith(matrix.service, 'services/react' ) }}  
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #v7.0.0
        with: 
          node-version-file: ${{ matrix.service }}/package.json
          cache: "npm"
          cache-dependency-path: ${{ matrix.service }}/package-lock.json

      - name: Setup go
        if: ${{ startsWith(matrix.service, 'services/go') }}  
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e #v7.0.0
        with:
            go-version-file: ${{ matrix.service }}/go.mod
            cache-dependency-path: ${{ matrix.service }}/go.sum

      - name: Install poetry
        if: ${{ startsWith(matrix.service, 'services/python') }}  
        uses: snok/install-poetry@a783c322200f0519c7926aa6faa857c4e23e9263 #v1.4.2

      - name: Install python
        if: ${{ startsWith(matrix.service, 'services/python') }}  
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 #v7.0.0 
        with:
            python-version-file: ${{ matrix.service }}/pyproject.toml
            cache: poetry
            cache-dependency-path: ${{ matrix.service }}/poetry.lock
        
      - name: Install Task/ setup Binary
        uses: supplypike/setup-bin@8365380a806a88e7a0f0d07059b175ca2f5418d7 #v5.0.1 
        with:
            uri: https://github.com/go-task/task/releases/download/v3.53.1/task_linux_amd64.tar.gz
            name: task
            version: v3.53.1

      - name: Install app deps
        working-directory: ${{ matrix.service }}
        run: |
          task install-ci

      - name: run tests
        working-directory: ${{ matrix.service }}
        run: |
          task test
